services:
  - type: web
    name: fluentpass
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    domains:
      - fluentpass.onrender.com

